blank_issues_enabled: false
contact_links:
  - name: "ğŸ“§ Support"
    url: "https://github.com/AssetCool/.github/blob/main/README.md"
    about: "Issue type usage and support email address can be found here."
