blank_issues_enabled: false
contact_links:
  - name: "ðŸ“§ Support"
    url: "https://github.com/AssetCool/.github/blob/main/README.md"
    about: "Support/guidance over which issue type to use can be found here."
